### ISSUE TITLE
https://deno.land/x/nanoid not available

### ISSUE THREAD

**Issue by tiagodll** [ianfabs/nanoid#10]
the package is now invalid.
When I try to import it, is returning 
``No uploaded versions
This module name has been reserved for a repository, but no versions have been uploaded yet. Modules that do not upload a version within 30 days of registration will be removed. If you are the owner of this module, please re-add the GitHub repository with deno.land/x (by following the instructions at https://deno.land/x#add), and publish a new version.``

**Comment by ianfabs** [comment]
@tiagodll It seems it's been taken off of the deno third party modules repo. I will try adding it back now

**Comment by ianfabs** [comment]
@tiagodll I was able to get it back up and running! I also updated the code with some breaking changes. No more default exports. Other than than you should be good to go!

**Comment by tiagodll** [comment]
Thanks!
